# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      sudo apt-get install repo
      mkdir coral && cd coral
      repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b warrior
      repo sync
      git clone https://github.com/kraj/meta-clang.git sources/meta-clang -b warrior
      git clone https://github.com/mirzak/meta-coral.git sources/meta-coral -b warrior
      echo "ACCEPT_FSL_EULA = 1" >> conf/local.conf
      MACHINE=coral-dev DISTRO=fslc-wayland source ./setup-environment build
      read -n 6 -s -r -p "Press any key to continue"
      echo 'BBLAYERS += "${BSPDIR}/sources/meta-clang"' >> conf/bblayers.conf
      echo 'BBLAYERS += "${BSPDIR}/sources/meta-coral"' >> conf/bblayers.conf
      bitbake core-image-base
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

